#!/bin/bash

mem() {
    mem_used="$(free -h | grep 'Mem' | cut -c28-31)"
    mem_total="$(free -h | grep Mem | cut -c17-19)"
    echo -ne "Î ${mem_used}/${mem_total}"
}

BATTERY_NOTIFY_LAST_TIME="$(date +%s)"

battery_notify() {
  status="$(cat /sys/class/power_supply/AC/online)"
  battery="$(cat /sys/class/power_supply/BAT0/capacity)"
  if [[ "${status}" == 0 ]]; then
    if [ ${battery} -le 20 -a $(($(date +%s) - $BATTERY_NOTIFY_LAST_TIME)) -ge 90 ]; then
      BATTERY_NOTIFY_LAST_TIME="$(date +%s)"
      notify-send 'Low Battery!' "Battery Level: ${battery}%" -u critical
    fi
  fi
}

power() {
  status="$(cat /sys/class/power_supply/AC/online)"
  battery="$(cat /sys/class/power_supply/BAT0/capacity)"
  if [ "${status}" == 1 ]; then
    echo -ne "Â ${battery}%"
  else
    echo -ne "ð ${battery}%"
  fi
}

wifi() {
  ssid="$(iwgetid -r)"
  if [ ${ssid} ]; then
    echo -ne "¤ ${ssid}"
  else
    echo -ne "¤ NO NETWORK"
  fi
}

hddfree() {
  hddfree="$(df -Ph /dev/nvme0n1p2 | awk '$3 ~ /[0-9]+/ {print $4}')"
  echo -ne "¨ ${hddfree}"
}

volume(){
    if pamixer --get-mute >/dev/null; then
      echo -en "í OFF"
    else
      echo -en "í $(pamixer --get-volume)%"
    fi
 }

datetime() {
  datetime="$(date "+%d/%m/%Y %H:%M:%S")"
  echo -ne "É ${datetime}"
}

while true; do
  xsetroot -name "$(mem)  $(hddfree)  $(wifi)  $(volume)  $(power)  $(datetime)"
  battery_notify
  sleep 1
done
