#!/bin/bash

mem() {
    mem_used="$(free -h | grep 'Mem' | cut -c28-31)"
    mem_total="$(free -h | grep Mem | cut -c16-19)"
    echo -ne "Î ${mem_used}/${mem_total}"
}

power() {
  status="$(cat /sys/class/power_supply/AC/online)"
  battery="$(cat /sys/class/power_supply/BAT0/capacity)"
  if [ "${status}" == 1 ]; then
    echo -ne "Â ${battery}%"
  else
    echo -ne "ð ${battery}%"
  fi
}

wifi() {
  ssid="$(iwgetid -r)"
  if [ ${ssid} ]; then
    echo -ne "¤ ${ssid}"
  else
    echo -ne "¤ NO NETWORK"
  fi
}

hddfree() {
  hddfree="$(df -Ph /dev/sda1 | awk '$3 ~ /[0-9]+/ {print $4}')"
  echo -ne "¨ ${hddfree}"
}

volume(){
    if pamixer --get-mute >/dev/null; then
      echo -en "í OFF"
    else
      echo -en "í $(pamixer --get-volume)%"
    fi
 }

datetime() {
  datetime="$(date "+%d/%m/%Y %H:%M:%S")"
  echo -ne "É ${datetime}"
}


while true; do
  xsetroot -name "$(mem)  $(hddfree)  $(wifi)  $(volume)  $(power)  $(datetime)"
  sleep 1
done
