#!/bin/bash

# wert_dwm startup script

export QT_QPA_PLATFORMTHEME="qt5ct"
export MOZ_USE_XINPUT2=1
 
xset +fp ~/.dwm/fonts/
xset fp rehash

xbacklight -set 8
setxkbmap -variant altgr-intl us

# Set touchscreen to control only the integrated LCD
xinput --map-to-output 'ELAN Touchscreen' eDP1

wmname LG3D
compton -b
dunst &

[[ -e ~/.fehbg ]] && ~/.fehbg || feh --bg-scale ~/.dwm/images/bg.jpg

~/.dwm/dwm-statusbar &
exec ssh-agent ~/.dwm/dwm
